#ifndef LORAMESHCONFIGURATION_H
#define LORAMESHCONFIGURATION_H

#if !defined(SIMULATION)
#define USE_MEGA defined(ARDUINO_ARCH_AVR)
#define USE_ESP32 defined(ARDUINO_ARCH_ESP32)
#define USE_ARDUINO 1
#else
#define USE_ARDUINO 0
#endif // SIMULATION

#define USE_ETL USE_ARDUINO

#endif // LORAMESHCONFIGURATION_H